# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('abstract', models.TextField(max_length=1024, verbose_name='摘要')),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalItem',
            fields=[
                ('basicitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.BasicItem')),
                ('context', models.TextField(help_text='文章的正文内容', verbose_name='正文')),
                ('sequence', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2)], max_length=1, verbose_name='顺序')),
                ('cover', models.ForeignKey(help_text='文章的封面图标', on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
            ],
            bases=('homepage.basicitem',),
        ),
        migrations.CreateModel(
            name='VerticalItem',
            fields=[
                ('basicitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.BasicItem')),
                ('title2', models.CharField(blank=True, max_length=64, null=True, verbose_name='副标题')),
                ('sequence', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2)], max_length=1, verbose_name='顺序')),
                ('cover', models.ForeignKey(help_text='文章的封面图标', on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
            ],
            bases=('homepage.basicitem',),
        ),
    ]
